apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush              1
        Log_Level          info
        Parsers_File       parsers.conf

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Rotate_Wait      30

    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_Tag_Prefix  kube.var.log.containers.
        Merge_Log        On
        K8S-Logging.Parser  On

    [OUTPUT]
        Name             http
        Match            *
        Host             ${SPLUNK_HEC_HOST}
        Port             8088
        URI              /services/collector/event
        Header           Authorization Bearer ${SPLUNK_HEC_TOKEN}
        Format           json
        tls              On
        tls.verify       Off
        Retry_Limit      False
        compress         gzip

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
